### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#989] opened 2023-03-21 10:03 UTC
The UI tells me that an email has been sent but I didn't receive any email

![image](https://user-images.githubusercontent.com/13419481/226573720-dbc9b99c-dcea-4b80-a3c9-6635264e9a63.png)

**Comment by moshloop** [comment] 2023-03-21 10:22
Duplicate of https://github.com/flanksource/flanksource-ui/issues/987

**Comment by adityathebe** [comment] 2023-03-21 10:30
That's different. This is resetting your password whereas the issue you mentioned is about logging out.

**Closed** 2023-05-22 06:42 UTC
Labels: bugathon, extra large
